VERSION: "0.5.2"

SCRIPT:
  LANGUAGE: "en"
  LAUNCH_OPTIONS: ""
  SMTP_VERIFICATION: true
  IMAGE_VERIFICATION: true
  SNAG_DETECTION: true
  SPOOLING_DETECTION: true
  RANDOM_ROD_SELECTION: true
  SPOOL_CONFIDENCE: 0.98
  SPOD_ROD_RECAST_DELAY: 1800
  LURE_CHANGE_DELAY: 1800
  ALARM_SOUND: "./static/sound/guitar.wav"
  RANDOM_CAST_PROBABILITY: 0.25
  SCREENSHOT_TAGS:
    - "green"
    - "yellow"
    - "blue"
    - "purple"
    - "pink"

KEY:
  TEA: -1
  CARROT: -1
  BOTTOM_RODS: [1, 2, 3]
  COFFEE: 4
  DIGGING_TOOL: 5
  ALCOHOL: 6
  MAIN_ROD: 1
  SPOD_ROD: 7
  QUIT: "CTRL-C"

STAT:
  ENERGY_THRESHOLD: 0.74
  HUNGER_THRESHOLD: 0.5
  COMFORT_THRESHOLD: 0.51
  TEA_DELAY: 300
  COFFEE_LIMIT: 10
  COFFEE_PER_DRINK: 1
  ALCOHOL_DELAY: 900
  ALCOHOL_PER_DRINK: 1

FRICTION_BRAKE:
  INITIAL: 29
  MAX: 30
  START_DELAY: 2.0
  INCREASE_DELAY: 1.0
  SENSITIVITY: "medium"

KEEPNET:
  CAPACITY: 100
  FISH_DELAY: 0.0
  GIFT_DELAY: 4.0
  FULL_ACTION: "quit"
  WHITELIST:
    - "mackerel"
    - "saithe"
    - "herring"
    - "squid"
    - "scallop"
    - "mussel"
  BLACKLIST: []
  TAGS:
    - "green"
    - "yellow"
    - "blue"
    - "purple"
    - "pink"

NOTIFICATION:
  EMAIL: "email@example.com"
  PASSWORD: "password"
  SMTP_SERVER: "smtp.gmail.com"
  MIAO_CODE: "example"
  DISCORD_WEBHOOK_URL: ""

PAUSE:
  DELAY: 1800
  DURATION: 600

PROFILE:
  SPIN:
    MODE: "spin"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 6.0
    TIGHTEN_DURATION: 0.0
    RETRIEVAL_DURATION: 0.0
    RETRIEVAL_DELAY: 0.0
    RETRIEVAL_TIMEOUT: 256.0
    PRE_ACCELERATION: false
    POST_ACCELERATION: "off"
    TYPE: "normal"
  SPIN_WITH_PAUSE:
    MODE: "spin"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 6.0
    TIGHTEN_DURATION: 1.0
    RETRIEVAL_DURATION: 1.0
    RETRIEVAL_DELAY: 3.0
    RETRIEVAL_TIMEOUT: 256.0
    PRE_ACCELERATION: false
    POST_ACCELERATION: "off"
    TYPE: "pause"
  SPIN_WITH_LIFT:
    MODE: "spin"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 6.0
    TIGHTEN_DURATION: 0.0
    RETRIEVAL_DURATION: 1.0
    RETRIEVAL_DELAY: 1.0
    RETRIEVAL_TIMEOUT: 256.0
    PRE_ACCELERATION: false
    POST_ACCELERATION: "off"
    TYPE: "lift"
  BOTTOM:
    MODE: "bottom"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 4.0
    POST_ACCELERATION: "off"
    CHECK_DELAY: 32.0
    CHECK_MISS_LIMIT: 16
    PUT_DOWN_DELAY: 0.0
  PIRK:
    MODE: "pirk"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 60.0
    TIGHTEN_DURATION: 1.0
    DEPTH_ADJUST_DELAY: 4.0
    DEPTH_ADJUST_DURATION: 1.0
    CTRL: false
    SHIFT: false
    PIRK_DURATION: 0.5
    PIRK_DELAY: 2.0
    PIRK_TIMEOUT: 32.0
    PIRK_RETRIEVAL: false
    HOOK_DELAY: 0.5
    POST_ACCELERATION: "auto"
  PIRK_WITH_RETRIEVAL:
    MODE: "pirk"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 60.0
    TIGHTEN_DURATION: 1.0
    DEPTH_ADJUST_DELAY: 0.0
    DEPTH_ADJUST_DURATION: 1.0
    CTRL: false
    SHIFT: false
    PIRK_DURATION: 0.5
    PIRK_DELAY: 2.0
    PIRK_TIMEOUT: 32.0
    PIRK_RETRIEVAL: true
    HOOK_DELAY: 0.5
    POST_ACCELERATION: "auto"
  WAKEY_RIG:
    MODE: "pirk"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 45.0
    TIGHTEN_DURATION: 1.0
    DEPTH_ADJUST_DELAY: 4.0
    DEPTH_ADJUST_DURATION: 1.0
    CTRL: true
    SHIFT: false
    PIRK_DURATION: 1.5
    PIRK_DELAY: 4.0
    PIRK_TIMEOUT: 32.0
    PIRK_RETRIEVAL: false
    HOOK_DELAY: 0.5
    POST_ACCELERATION: "auto"
  ELEVATOR:
    MODE: "elevator"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 60.0
    TIGHTEN_DURATION: 1.0
    ELEVATE_DURATION: 4.0
    ELEVATE_DELAY: 4.0
    ELEVATE_TIMEOUT: 40.0
    DROP: false
    HOOK_DELAY: 0.5
    POST_ACCELERATION: "auto"
  ELEVATOR_WITH_DROP:
    MODE: "elevator"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 60.0
    TIGHTEN_DURATION: 1.0
    ELEVATE_DURATION: 4.0
    ELEVATE_DELAY: 4.0
    ELEVATE_TIMEOUT: 40.0
    DROP: true
    HOOK_DELAY: 0.5
    POST_ACCELERATION: "auto"
  TELESCOPIC:
    MODE: "telescopic"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 4.0
    FLOAT_SENSITIVITY: 0.68
    CHECK_DELAY: 1.0
    PULL_DELAY: 0.5
    DRIFT_TIMEOUT: 16.0
    CAMERA_SHAPE: "square"
  BOLOGNESE:
    MODE: "bolognese"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 4.0
    FLOAT_SENSITIVITY: 0.68
    CHECK_DELAY: 1.0
    PULL_DELAY: 0.5
    DRIFT_TIMEOUT: 32.0
    CAMERA_SHAPE: "square"
    POST_ACCELERATION: "off"
