SCRIPT:
  LAUNCH_OPTIONS: ""
  CONFIG_CONFIRMATION: true
  SMTP_VALIDATION: true
  IMAGE_VALIDATION: true

GENERAL:
  LANGUAGE: "en"
  KEEPNET_CAPACITY: 100
  SPOOL_CONFIDENCE: 0.985
  KEEP_FISH_DELAY: 1.0
  SNAG_DETECTION: true
  RANDOM_ROD_SELECTION: true
  SPOD_ROD_RECAST_DELAY: 1800
  LURE_CHANGE_DELAY: 1800
  KEEPNET_FULL_ACTION: "quit"
  ALARM_SOUND: "../static/sound/guitar.wav"
  RELEASE_WHITELIST:
    - "mackerel"
    - "saithe"
    - "herring"
    - "squid"
    - "scallop"
    - "mussel"

KEY:
  TEA: -1
  CARROT: -1
  RODS: [1, 2, 3]
  COFFEE: 4
  DIGGING_TOOL: 5
  ALCOHOL: 6
  MAIN_ROD: 1
  SPOD_ROD: 7
  QUIT: "CTRL-C"

STAT:
  ENERGY_THRESHOLD: 0.74
  HUNGER_THRESHOLD: 0.5
  COMFORT_THRESHOLD: 0.51
  COFFEE_LIMIT: 10
  COFFEE_PER_DRINK: 1
  ALCOHOL_DELAY: 900
  ALCOHOL_PER_DRINK: 1

FRICTION_BRAKE:
  INITIAL: 29
  MAX: 30
  START_DELAY: 2.0
  INCREASE_DELAY: 1.0

PAUSE:
  DELAY: 1800
  DURATION: 600

MODE:
  SPIN:
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 6.0
    TIGHTENING_DURATION: 1.0
    RETRIEVE_DURATION: 1.1
    RETRIEVE_DELAY: 3.0
    PRE_ACCELERATION: false
    POST_ACCELERATION: "off"

  BOTTOM:
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 4.0
    ACCELERATION: "off"
    CHECK_DELAY: 32.0

  PIRK:
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 60.0
    TIGHTEN_DURATION: 1.0
    PIRK_DURATION: 0.5
    PIRK_DELAY: 2.0
    PIRK_TIMEOUT: 32.0
    PIRK_TIMEOUT_ACTION: "adjust"
    ACCELERATION: "auto"
    HOOK_DELAY: 0.0
    TROLLING: "off"

  ELEVATOR:
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 60.0
    TIGHTEN_DURATION: 1.0
    ELEVATE_DURATION: 4.0
    ELEVATE_DELAY: 4.0
    ELEVEATE_TIMEOUT: 40.0
    ACCELERATION: "auto"
    HOOK_DELAY: 0.0
    TROLLING: "off"

  FLOAT:
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 4.0
    FLOAT_SENSITIVITY: 0.65
    CHECK_DELAY: 1.0
    PULL_DELAY: 0.5
    DRIFTING_TIMEOUT: 16.0
    CAMERA_SHAPE: "square"
